### ISSUE TITLE
Open for contributions?

### ISSUE THREAD

**Issue by phillipj** [meinside/rpi-camera-timelapse-go#1]
Hi there,

first of all thanks for the great project!

Really appreciate it, perfect for playing around with a raspberry and learning a little golang at the same time 👍 Like the simple approach of simply using `/usr/bin/raspistill` rather than interacting with the camera directly from go.

I just forked this project and played with it to be able to upload files to an AWS S3 bucket. I'm more than happy to contribute some of these changes back to your project if you're interested. Have a look at my current branch and let me know if anything seems interesting to you: [phillipj/rpi-camera-timelapse-go/commits/phillipj-changes](https://github.com/phillipj/rpi-camera-timelapse-go/commits/phillipj-changes).

**Comment by meinside** [comment]
Hi, and wow, thank you for your nice work!
I will look around and pull your codes into my repository.
I really like your S3 provider and the 'shoot within hours' option :-)

**Comment by phillipj** [comment]
Cool! I'm more than happy to open a couple of pull requests to contribute some of the features I've added, making it easier for you to just press the "merge" button instead 😄

As you like S3 and "shoot within hours", I'll start with those two.

**Comment by phillipj** [comment]
Seeing that you cherry picked some of the commits into your repo, I'll close this issue as you've clearly answered the question of this issue :)
