### ISSUE TITLE
config: default timeout value is very low

### ISSUE THREAD

**Issue by Gys** [meinside/rpi-camera-timelapse-go#3]
Hi

The default `config.json.sample` sets `--timeout` to `1`. But according to the docs (https://www.raspberrypi.org/documentation/raspbian/applications/camera.md) this value is expressed in milliseconds. The camera will work with a value of 1 ms, even on my Pi Zero, but the photo will be in a lower quality and maybe smaller. That is the tricky part. My Pi Zero needs at least 500 ms to fully prepare a photo.

I did not understand which settings caused the lower quality and it took me some experimenting to realize the problem was in the timeout. Maybe helpful for others :-)

**Comment by meinside** [comment]
Thank you for your pointing out! I wasn't aware of that detail.
Will fix it :-)
